# Utiliser une image de base appropriée (par exemple, node pour un projet Node.js)
FROM node:14

# Définir le répertoire de travail dans le conteneur
WORKDIR C:\Users\valen\Desktop\Projets\WebFilms\WebFilms

# Copier le fichier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances du projet
RUN npm install

# Copier le reste des fichiers du projet
COPY . .

# Exposer le port utilisé par l'application
EXPOSE 3000

# Démarrer l'application
CMD ["npm", "run", "dev"]
